### ISSUE TITLE
Fork privé impossible

### ISSUE THREAD

**Issue by alex-smtv** [cui-unige/outils-formels-modelisation#1]
Bonjour,

Voulant suivre la (bonne) idée de rendre le fork privé, j'aimerais signaler qu'il est à priori impossible de rendre privé un fork public, à moins d'avoir loupé quelque chose :
![fork-private](https://user-images.githubusercontent.com/13024466/31086769-0ee019f8-a79b-11e7-8aa4-f36187142f9f.png)

**Comment by kyouko-taiga** [comment]
Non, tu n'as rien raté. Il est malheureusement impossible de faire un fork privé dun dépôt public. Il s'agit là d'une limitation de GitHub malheureusement.
