### ISSUE TITLE
Erreur de build après avoir renommé mon dossier

### ISSUE THREAD

**Issue by ghost** [cui-unige/outils-formels-modelisation#11]
Bonsoir,

J'ai cette erreur après avoir renommé mon dossier taskmanager en TaskManager : 

error: PCH was compiled with module cache path '/home/koj/Dropbox/UNIGE/1er semestre/Outils formels/Github/outils-formels-modelisation/tp-01/**taskmanager**/.build/x86_64-unknown-linux/debug/ModuleCache/1PNUIE35HAM5Y', but the path is currently '/home/koj/Dropbox/UNIGE/1er semestre/Outils formels/Github/outils-formels-modelisation/tp-01/**TaskManager**/.build/x86_64-unknown-linux/debug/ModuleCache/1PNUIE35HAM5Y'

J'ai essayé : swift build --clean mais sans résultats. Les solutions que j'ai trouvé sont sur xcode que je n'utilise pas.

Merci 👍

**Comment by ghost** [comment]
J'ai résolu mon problème : 

swift build --no-static-swift-stdlib

**Comment by kyouko-taiga** [comment]
Hmm, ta solution semble n'avoir rien à voir avec le problème initial.

Le problème est que la target indiquée dans le package manifest (`Package.swift`) doit avoir le même nom que le dossier du projet. Dans les fichiers que j'ai délivré, le nom des deux est `TaskManager` et ne sont pas sensés être modifiés.
