### ISSUE TITLE
impossible de tirer des transitions depuis un CoverabilityMarking

### ISSUE THREAD

**Issue by staufga0** [cui-unige/outils-formels-modelisation#17]
Pour le TP 3, j'essaie de construire le CoverabilityGraph. Le problème et que je ne peut pas tirer de transition depuis  le marking passé en argument car c'est un CoverabilityMarking et pas un Marking, ce n'est donc pas un bon argument pour la transition.
Existe t-il un moyen de tirer des transition depuis un CoverabilityMarking vers un CoverabilityMarking ?

**Comment by QuentinRiv** [comment]
Personnellement, j'ai créé 2 fonctions : une qui transforme un Marking en CoverabilityMarking, et une autre qui fait l'opération inverse. De cette façon, on peut changer en graphe de couverture en graphe normal (et donc tirable), faire un tirage (sur un Marking) normal avec fire, puis revenir à un graphe de couverture. C'est un peu plus long, mais ça marche.
