### ISSUE TITLE
Problème pour lancer swift test

### ISSUE THREAD

**Issue by QuentinRiv** [cui-unige/outils-formels-modelisation#18]
Lorsque l'extension est finie et qu'elle marche (suite à quelques tests effectués dans le main), j'essaye de lancer Swift Test, afin de vérifier si mon programme marche bien.  Mais au moment de lancer, j'ai quelques messages d'erreur, empêchant de tester correctement, du type
error : module 'CoverabilityLibTests.allTests has no member named allTests
ou encore : error : value of optional type 'CoverabilityGarph' not unwrapped  (ce message est évitable en rajoutant un '!')
Y a-t-il un moyen de résoudre cela ?
Merci

**Comment by kyouko-taiga** [comment]
> J'ai quelques messages d'erreur, empêchant de tester correctement, du type error : module 'CoverabilityLibTests.allTests has no member named allTests

Fixed in ee6546874a27e95ab135b3a6cdedabe6c7b6641d

> ou encore : error : value of optional type 'CoverabilityGarph' not unwrapped (ce message est évitable en rajoutant un '!')

Je pense que ce bug vient de ton code, j'ai besoin de plus de contexte pour pouvoir t'aider. Peux-tu me montrer le code en question?
