### ISSUE TITLE
Comment lancer mon application

### ISSUE THREAD

**Issue by kyouko-taiga** [cui-unige/outils-formels-modelisation#2]
J'ai oublié de préciser comment lancer votre application, après avoir intégré PetriKit.

Tout d'abord, gardez à l'esprit que Swift est un language à compiler. S'il existe un REPL (la commande `swift` dans le terminal qui lance un interprète interactif) celui-ci n'est à utiliser que pour faire des petits tests simples et rapides. Si vous souhaitez créer une vraie application (ou librairie), il vous faudra passer par la création d'un package, puis par la compilation de ce package. C'est exactement ce que vous faites si vous suivez le [tutorial d'installation de PetriKit](https://github.com/kyouko-taiga/PetriKit/blob/master/README.md).

Une fois votre package créé, vous pouvez le compiler puis l'exécuter comme suit:

```bash
cd <path to your app>
swift build
.build/debug/<your app>
```

Par exemple, si votre application s'appelle `Koala` et qu'elle se situe dans votre home directory:

```bash
cd ~/Koala
swift build
.build/debug/Koala
```

Dans le cas du TP, des tests accompagnent le package que je vous ai fourni. Vous pouvez les exécuter avec la commande `swift test`.

**Comment by EspritOrgue** [comment]
![image](https://user-images.githubusercontent.com/7682637/31125297-2314dac8-a848-11e7-86ae-f31dee29cdfb.png)

Il y a une erreur lors de la compilation des test. (J'ai Swft 4.0)
![image](https://user-images.githubusercontent.com/7682637/31125436-96c65adc-a848-11e7-96c8-83dc1bf0c848.png)

**Comment by bastienfio** [comment]
Bonjour, j'ai les même erreurs. J'ai installé PetriKit en créant mon package Myapp. Le build a fonctionné. Maintenant que faut-il faire ? Comment utiliser le Taskmanager avec PetriKit ? 
Lors du `swift build` du task manager : `error: missingLinuxMain`. 
Dans quel répertoire devont nous utiliser la commande `swift test` ?
Avec swift test dans le petrikit, puisqu'il n'y a pas de fichier, cela ne sert à rien, et dans le taskManager, j'ai aussi l'erreur : `missingLinuxMain`. 
Merci d'avance.

**Comment by bastienfio** [comment]
Alors, en rajoutant un fichier dans le dossier du TaskManager nommé `LinuxMain.swift` là où il y a Package.swift, le `swift build` a fonctionné.

Ensuite, que doit donner le `swift test` ? Voici ce que j'ai : rien !
![image](https://user-images.githubusercontent.com/23053071/31221397-df613a38-a9c3-11e7-803d-f7a27c5bb8e4.png)

Sinon, toujours les mêmes questions, maintenant que faut-il faire ? Comment utiliser le Taskmanager avec PetriKit ? Quel fichier devons nous modifier pour le TP ?

**Comment by kyouko-taiga** [comment]
Fixed in 5e20c6c9e844f90c4a6bddb72315037e197a28f6

**Comment by kyouko-taiga** [comment]
> Sinon, toujours les mêmes questions, maintenant que faut-il faire ? Comment utiliser le Taskmanager avec PetriKit ? Quel fichier devons nous modifier pour le TP ?

Tâchez de ne pas poser des questions qui n'ont pas un rapport direct avec l'issue.
Ouvrez une autre issue au besoin.
