### ISSUE TITLE
Note tp-01

### ISSUE THREAD

**Issue by terryvogelsang** [cui-unige/outils-formels-modelisation#20]
Bonjour,

Je n'ai pas reçu de note pour mon tp-01.

Pourriez-vous me la communiquer svp ?

Merci d'avance

**Comment by kyouko-taiga** [comment]
Tu n'as pas activé le tab "issues". Je ne peux donc pas y laisser ta note.

**Comment by terryvogelsang** [comment]
<img width="588" alt="screen shot 2017-11-09 at 18 52 27" src="https://user-images.githubusercontent.com/17734492/32621155-36d3a98c-c57f-11e7-863d-6874673743e4.png">

Elles semblent pourtant activées chez moi.
