### ISSUE TITLE
Solution tp-03

### ISSUE THREAD

**Issue by kyouko-taiga** [cui-unige/outils-formels-modelisation#24]
Une solution pour le tp-03 vous est proposée ici: https://github.com/cui-unige/outils-formels-modelisation/blob/36622612910a9176224b7f669c5daf20e45da8c0/tp-03/Coverability/Sources/CoverabilityLib/PTNet%2BExtensions.swift

N'hésitez pas à la consulter!

**Comment by consolethinks** [comment]
Mais maintenant si quelqun essaie de faire un git pull, il y aura des problemes pour les personnes qui ont rendu le tp-03. Dans ce cas, est-ce qu'il faut ecraser nos propres solutions?

**Comment by kyouko-taiga** [comment]
Vous pouvez merge et choisir de conserver votre solution.
