### ISSUE TITLE
Le Triangle Amoureux - TP06

### ISSUE THREAD

**Issue by consolethinks** [cui-unige/outils-formels-modelisation#26]
Bonjour!
Je me pose la question, quelle définition du triangle amoureux devrait on utiliser dans le TP06? Selon plusieurs sites, ça peut signifier 2 personnes, a et b, amie c, ou a aime b aime c aime a entre d'autres relations triangulaire. Et est-ce qu'une triangle amoureux est toujours considéré comme telle s'il y a une quatrième personne d qui a une relation avec une des personnes dans le triangle?
Merci en avance

**Comment by kyouko-taiga** [comment]
La définition entendue par le TP peut être énoncée comme: "A aime B qui aime C qui aime A".
