### ISSUE TITLE
Question TP6

### ISSUE THREAD

**Issue by QuentinRiv** [cui-unige/outils-formels-modelisation#27]
Bonjour, 
J'aurai quelques questions sur le TP6 : 

1. Il est dit "Robin aime une personne dans un triangle amoureux". Est-ce que Robin se trouve dans ce trouve dans ce triangle, ou non ? Ou alors, pouvons choisir si c'est le cas ?

2. Il est aussi dit qu'un certain "Alex" a un frère caché. De quel Alex s'agit-il, puisque Alexandre et Alexandrine sont tous les deux surnommés "Alex" ?
 
3. Pour la saison 2 (Question 3), faut-il faire la preuve (à l'aide des séquents) en se basant sur le graphe que l'on a fait avant, à la question 2, (et donc une situation précise où toutes les relations sont marquées) , ou faut-il considérer l'ensemble des possibilités, en reprenant les informations générales données avant ?

Merci

**Comment by kyouko-taiga** [comment]
1. Pas nécessairement.
2. Il s'agit d'Alexandre.
3. Il faut considérer l'ensemble des possibilités. Vous pouvez néanmoins utiliser votre graphe (si vous êtes sûrs qu'il est correct) pour vérifier votre réponse et/ou vous guider dans l'écriture de votre preuve.

**Comment by QuentinRiv** [comment]
Merci pour les réponses.
Pour autant, s'il s'agit d'Alexandre qui a un frère caché, il est tout à fait possible de prouver qu'il existe un graphe dans lequel il n'y pas d'inceste (Alexandre n'aime ni Miguel, ni Robin), et Miguel aime Floriane. Or, il faut justement prouver que cela est faux (non ?)
Tandis que si c'est Alexandrine qui a un frère caché, alors, dans ce cas-là, il est prouvable que l'ami a tord (ie. il y a un inceste ou Miguel n'aime pas Floriane)
