### ISSUE TITLE
Mettre à jour le readme pour créer un mirror repo privé

### ISSUE THREAD

**Issue by terryvogelsang** [cui-unige/outils-formels-modelisation#3]
Hello,

Pourriez-vous svp mettre à jour le readme pour que chacun puisse faire qqch similaire au fork privé que vous demandiez à la base ?

Les étapes sont les suivantes :

- Cloner le repo original avec l'option --bare
`git clone --bare https://github.com/cui-unige/outils-formels-modelisation.git`

 - Créer ensuite un repo privé sur votre GitHub personnel avec comme nom : outils-formels-modelisation

- Se rendre dans le repo original cloné en local
`cd votre-repo-original-local`

- Push une version mirror du repo original sur votre GitHub
`git push --mirror https://github.com/votreusername/outils-formels-modelisation.git`

- Supprimer le repo original cloné en local 

- Cloner le repo de votre GitHub en local 
`git clone https://github.com/votreusername/outils-formels-modelisation.git`

- Inviter les assistants/moniteurs/profs pour qu'ils puissent consulter votre repo (Pourriez-vous svp nous donner les usernames concernés ?)

**Comment by kyouko-taiga** [comment]
J'ai spécifié la marche à suivre pour fork le dépôt dans le README.
Je vous prie de ne pas faire de dépôt privé, mais de fork publiquement celui-ci.
