### ISSUE TITLE
comment tester main

### ISSUE THREAD

**Issue by CelineRenaud** [cui-unige/outils-formels-modelisation#7]
J'ai bien tout tester pour que les différentes applications compilent, mais je ne sais pas comment lancé main pour voir si tout fonctionne bien comme je le prédit.

Je vois pas forcément de parallèlisme avec swift test pour les différents test...

**Comment by kyouko-taiga** [comment]
La commande `swift test` permet d'exécuter les tests du répertoire `Test/` et la commande `swift build` permet de compiler les sources et créer les exécutables du projet. Ceux-ci sont spécifiés par le package manifest (`Package.swift`).

Le exécutables sont enregistrés dans le répertoire `.build/[release|debug]`.
Par exemple, si on effectue la commande `swift build` dans le répertoire du TaskManager (TP1), on trouve l'exécutable `.build/debug/TaskManager`.

Pour lancer ton programme, il faut donc exécuter les commandes suivantes:

```bash
swift build
.build/debug/TaskManager
```
